---
# 3.8 required for the volume relative path name to config file 
# docker compose build
# docker compose up -d
version: '3.8'

services:
  src:
    extends: 
      file: ${DOCKERDEV_BASEDIR}/pg/docker-pg.yaml
      service: pg
    build: .
    hostname: pg-src
    volumes:
      - ${DOCKERDEV_BASEDIR}/pg/init.d:/docker-entrypoint-initdb.d        
      - src:/var/lib/postgresql/data    
    networks:
      default:
        aliases: 
          - pg
          - pg-src
          - postgresql
          
  dst:
    extends: 
      file: ${DOCKERDEV_BASEDIR}/pg/docker-pg.yaml
      service: pg
    deploy:
      mode: replicated
      replicas: 0           
    image: postgres:16.0
    hostname: pg-dst
    volumes:
      - ${DOCKERDEV_BASEDIR}/pg/init.d:/docker-entrypoint-initdb.d        
      - dst:/var/lib/postgresql/data
    networks:
      default:
        aliases: 
          - pg-dst

networks:
  default:
    name: arcnet
    external: true
volumes:
  src:
  dst:
