---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  v1102:
    # sys and system password: oracle
    image: oracleinanutshell/oracle-xe-11g
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: oraxe
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 1521
      - 5500
    environment:
      - ORACLE_PWD=oracle # harded coded and cannot change
      - ORACLE_SID=XE
      # for the init script
      - ARCHREDO=/u01/app/oracle/oradata/XE/arch
      - REDO=/u01/app/oracle/oradata/XE
      - FOOTER_LINES=3      
    env_file:
      - ../../config/env.sh          
    volumes:
      - ../init.d:/docker-entrypoint-initdb.d

networks:
  default:
    name: arcnet
    external: true


  # https://stackoverflow.com/questions/39663096/docker-compose-creating-multiple-instances-for-the-same-image
