---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  nfs:
    image: itsthenetwork/nfs-server-alpine:latest
    container_name: nfs
    ports:
      - 2049
    cap_add:
      - SYS_ADMIN
    environment:
      - SHARED_DIRECTORY=/nfsshare 
    volumes:
      - nfsdata:/nfsshare
  nfsclient:
    image: alpine
    
  oraxe:
    image: oracle/database:21.3.0-xe
    container_name: oraxe
    ports:
      - 1521
      - 5500
    environment:
      - ORACLE_PWD=Passw0rd 
    volumes:
      - type: volume
        source: oranfs
        target: /opt/oracle/oradata
        volume:
          nocopy: true
    depends_on:
      - nfs  
networks:
  default:
    name: arcnet
    external: true
volumes:
  oranfs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs,rw,bg,hard,tcp,vers=3,timeo=600,rsize=32768,wsize=32768,actimeo=0
      device: nfsdata:/oradata
  nfsdata:
  nfsexports:



# https://github.com/oracle/docker-images/blob/7175aecdde7cd95af85be96b0a6dff3173d9d0d8/OracleDatabase/RAC/OracleRACStorageServer/README.md
