---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  oraxe:
    image: oracle/database:21.3.0-xe
    container_name: oraxe
    ports:
      - :1521
      - :5500
    environment:
      - ORACLE_PWD=Passw0rd 
    volumes:
      - oraxe:/opt/oracle/oradata

networks:
  default:
    name: arcnet
    external: true
volumes:
  oraxe:
