---
# 3.8 required for the volume relative path name to config file 
version: '3.8'

services:
  src:
    extends: 
      file: ../docker-mysql.yaml
      service: mysql  
    image: mysql:5.7.42
    hostname: mysql-src
    volumes:
      - ../init.d:/docker-entrypoint-initdb.d
      - src:/var/lib/mysql 
    command: 
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=true                    # allow load data local
      - --secure-file-priv=/tmp                # allow load data

  dst:
    extends: 
      file: ../docker-mysql.yaml
      service: mysql  
    deploy:
      mode: replicated
      replicas: 0        
    image: mysql:5.7.42
    hostname: mysql-dst
    volumes:
      - ../init.d:/docker-entrypoint-initdb.d
      - dst:/var/lib/mysql
    command: 
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=true                    # allow load data local
      - --secure-file-priv=/tmp                # allow load data

networks:
  default:
    name: arcnet
    external: true
    
volumes:    
  src:  
  dst:  
