---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  nfs:
    image:  erichough/nfs-server
    cap_add:
      - SYS_ADMIN
    container_name: nfs
    ports:
      - 2049
    volumes:
      - nfs:/export
      - ./etc/exports.txt:/etc/exports:ro
    networks:
      nfs-server-bridge:
        ipv4_address: 192.168.1.2  
  ubuntu:
    image: ubuntu
    cap_add:
      - SYS_ADMIN
    tty: true
    command: "/bin/bash"   
    networks:
      nfs-server-bridge: null     
    volumes:
    - type: volume
      source: ubuntu-1-volume
      target: /nfs/test_share    
    depends_on:
      nfs:
        condition: service_started

networks:
  default:
    name: arcnet
    external: true
  nfs-server-bridge:
    name: nfs-server-bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.1.0/24    
volumes:
  nfs:    
  ubuntu-1-volume:
    name: ubuntu-1-volume
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.2"
      device: ":/export"  
                                   

   