---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  metadata:
    image: postgres:14-alpine
    container_name: arcion-metadata
    ports:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Passw0rd 
      - PGCLIENTENCODING=utf-8
    volumes:
      - arcion-metadata:/var/lib/postgresql/data
      - ./init.d:/docker-entrypoint-initdb.d

  ui:
    image:  arcionlabs/replicant-on-premises
    container_name: ui
    ports:
      - 8080:8080
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Passw0rd 
      - ARCION_LICENSE=${ARCION_LICENSE}
      - DB_HOST=arcion-metadata
      - DB_PORT=5432
      - DB_DATABASE=arcion
      - DB_USERNAME=arcion
      - DB_PASSWORD=Passw0rd
    volumes:
      - arcion-share-data:/data
      - arcion-share-config:/config
      - arcion-share-libs:/libs
    depends_on:
      - metadata  

  workloads:
    image:  robertslee/arcdemo
    container_name: workloads
    ports:
      - 7681:7681
    environment:
      - ARCION_LICENSE=${ARCION_LICENSE}
      - LANG=C.UTF-8
      - PGCLIENTENCODING=utf-8

      # confluent
      - CFLT_SRC_ID=$CFLT_SRC_ID
      - CFLT_SRC_SECRET=$CFLT_SRC_SECRET
      - CFLT_SRC_ENDPOINT=$CFLT_SRC_ENDPOINT

      - CFLT_DST_ID=$CFLT_DST_ID
      - CFLT_DST_SECRET=$CFLT_DST_SECRET
      - CFLT_DST_ENDPOINT=$CFLT_DST_ENDPOINT

      # minio
      - MINIO_SRC_ID=$MINIO_SRC_ID
      - MINIO_SRC_SECRET=$MINIO_SRC_SECRET
      - MINIO_SRC_ENDPOINT=$MINIO_SRC_ENDPOINT
  
      - MINIO_DST_ID=$MINIO_DST_ID
      - MINIO_DST_SECRET=$MINIO_DST_SECRET
      - MINIO_DST_ENDPOINT=$MINIO_DST_ENDPOINT

      # Snowflake
      - SNOW_SRC_ID=$SNOW_SRC_ID
      - SNOW_SRC_SECRET=$SNOW_SRC_SECRET
      - SNOW_SRC_ENDPOINT=$SNOW_SRC_ENDPOINT
      - SNOW_SRC_WAREHOUSE=$SNOW_SRC_WAREHOUSE

      - SNOW_DST_ID=$SNOW_DST_ID
      - SNOW_DST_SECRET=$SNOW_DST_SECRET
      - SNOW_DST_ENDPOINT=$SNOW_DST_ENDPOINT
      - SNOW_DST_WAREHOUSE=$SNOW_DST_WAREHOUSE

      # Google Big Query the key is gzip | base64 -w 0
      - GBQ_SRC_LOCATION=$GBQ_SRC_LOCATION	
      - GBQ_SRC_SECRET=$GBQ_SRC_SECRET
      - GBQ_SRC_ENDPOINT=$GBQ_SRC_ENDPOINT

      - GBQ_DST_LOCATION=$GBQ_DST_LOCATION	
      - GBQ_DST_SECRET=$GBQ_DST_SECRET
      - GBQ_DST_ENDPOINT=$GBQ_DST_ENDPOINT
      # AWS
      - AWS_SRC_ID=$AWS_SRC_ID
      - AWS_SRC_SECRET=$AWS_SRC_SECRET

      - AWS_DST_ID=$AWS_DST_ID
      - AWS_DST_SECRET=$AWS_DST_SECRET      
    volumes:
      - arcion-share-data:/data
      - arcion-share-config:/config
      - arcion-share-libs:/libs
      - arcion-share-loadgen:/arcion/data
    depends_on:
      - metadata  

networks:
  default:
    name: arcnet
    external: true
volumes:
  arcion-metadata:
  arcion-share-data:
  arcion-share-config:
  arcion-share-libs:
  arcion-share-loadgen:
