---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  pg:
    build: .
    container_name: postgresql
    ports:
      - :5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Passw0rd 
    volumes:
      - pg:/var/lib/postgresql/data
      - ./init.d:/docker-entrypoint-initdb.d
    command: 
      - postgres
      - "-c" 
      - wal_level=logical
      - "-c" 
      - max_replication_slots=10
      - "-c" 
      - max_connections=300
      - "-c" 
      - shared_buffers=80MB
      - "-c" 
      - ssl=on
      - "-c" 
      - ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      - "-c" 
      - ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

networks:
  default:
    name: arcnet
    external: true
volumes:
  pg:

