---
# 3.8 required for the volume relative path name to config file 
# the build adds wal2json 
version: '3.8'

services:
  src:
    extends: 
      file: ../docker-pg.yaml
      service: pg    
    build: .
    hostname: pg-src
    volumes:
      - ../init.d:/docker-entrypoint-initdb.d        
      - src:/var/lib/postgresql/data 
    networks:
      default:
        aliases: 
          - pg
          - pg-src
          - postgresql      

  dst:
    extends: 
      file: ../docker-pg.yaml
      service: pg    
    deploy:
      mode: replicated
      replicas: 0       
    image: postgres:13.11
    hostname: pg-dst
    volumes:
      - ../init.d:/docker-entrypoint-initdb.d        
      - dst:/var/lib/postgresql/data
    networks:
      default:
        aliases: 
          - pg-dst
          
networks:
  default:
    name: arcnet
    external: true
volumes:
  src:  
  dst:  
