---
# 3.8 required for the volume relative path name to config file 
# the build adds wal2json 
version: '3.8'
services:
  v153:
    build: Dockerfile.v153
    ports:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Passw0rd 
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    command: 
      - postgres
      - "-c" 
      - wal_level=logical
      - "-c" 
      - max_replication_slots=10
      - "-c" 
      - max_connections=300
      - "-c" 
      - shared_buffers=80MB
      - "-c" 
      - ssl=on
      - "-c" 
      - ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      - "-c" 
      - ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

  v148:
    build: 
    ports:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Passw0rd 
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    command: 
      - postgres
      - "-c" 
      - wal_level=logical
      - "-c" 
      - max_replication_slots=10
      - "-c" 
      - max_connections=300
      - "-c" 
      - shared_buffers=80MB

networks:
  default:
    name: arcnet
    external: true

