---
# 3.8 required for the volume relative path name to config file 
# the build adds wal2json 
version: '3.8'

services:
  v1311-src:
    extends: 
      file: ./docker-pg.yaml
      service: pg    
    build: v1311
    hostname: pg-src
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d        
      - v1311-src:/var/lib/postgresql/data 

  v1311-dst:
    extends: 
      file: ./docker-pg.yaml
      service: pg    
    deploy:
      mode: replicated
      replicas: 0       
    image: postgres:13.11
    hostname: pg-dst
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d        
      - v1311-dst:/var/lib/postgresql/data

networks:
  default:
    name: arcnet
    external: true
volumes:
  v1311-src:  
  v1311-dst:  
