---
# 3.8 required for the volume relative path name to config file 
# the build adds wal2json 
version: '3.8'
services:
  v1503:
    build: v1503
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: postgresql
    deploy:
      mode: replicated
      replicas: 1    
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=Passw0rd 
    env_file:
      - ../config/env.sh      
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    command: 
      - postgres
      - "-c" 
      - wal_level=logical
      - "-c" 
      - max_replication_slots=10
      - "-c" 
      - max_connections=300
      - "-c" 
      - shared_buffers=80MB
      - "-c" 
      - ssl=on
      - "-c" 
      - ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
      - "-c" 
      - ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

  v1408:
    build: v1408
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: postgresql
    deploy:
      mode: replicated
      replicas: 1    
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=Passw0rd 
    env_file:
      - ../config/env.sh      
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    command: 
      - postgres
      - "-c" 
      - wal_level=logical
      - "-c" 
      - max_replication_slots=10
      - "-c" 
      - max_connections=300
      - "-c" 
      - shared_buffers=80MB

  v1311:
    build: v1311
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: postgresql
    deploy:
      mode: replicated
      replicas: 1    
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=Passw0rd 
    env_file:
      - ../config/env.sh      
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    command: 
      - postgres
      - "-c" 
      - wal_level=logical
      - "-c" 
      - max_replication_slots=10
      - "-c" 
      - max_connections=300
      - "-c" 
      - shared_buffers=80MB

networks:
  default:
    name: arcnet
    external: true

