---
# 3.8 required for the volume relative path name to config file 
# this shares image pg-src-v1503  
# docker compose build
# docker compose up -d
version: '3.8'

services:
  v1503-src:
    extends: 
      file: ./docker-pg.yaml
      service: pg
    build: v1503
    hostname: pg-src
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d        
      - src-v1503:/var/lib/postgresql/data
    networks:
      default:
        aliases: 
          - pg
          - pg-src
          - postgresql
          
  v1503-dst:
    extends: 
      file: ./docker-pg.yaml
      service: pg
    image: postgres:15.3
    hostname: pg-dst
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d        
      - dst-v1503:/var/lib/postgresql/data
    networks:
      default:
        aliases: 
          - pg-dst

networks:
  default:
    name: arcnet
    external: true
volumes:
  src-v1503:
  dst-v1503:
