---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  v340:
    image: apache/spark:3.4.0-scala2.12-java11-python3-r-ubuntu
networks:
  default:
    name: arcnet
    external: true


