---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  oraxe:
    image: oracle/database:19.3.0-ee
    container_name: oraee
    ports:
      - 1521
      - 5500
    environment:
      - ORACLE_PWD=Passw0rd 
    volumes:
      - oraee1930:/opt/oracle/oradata

networks:
  default:
    name: arcnet
    external: true
volumes:
  oraee1930:
