---
version: '3'
services:
  informix:
    image: ibmcom/informix-developer-database:latest
    container_name: informix
    ports:
      - 9088:9088
      - :9089
      - :27017
      - :27018
      - :27883
    environment:
      - LICENSE=accept
networks:
  default:
    name: arcnet
    external: true
