---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  db2:
    image: ibmcom/db2
    container_name: db2
    privileged: true
    ports:
      - 50000
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=Passw0rd
      - DBNAME=db2inst1
    volumes:
      - ./init.d:/var/custom
      - db2:/database
networks:
  default:
    name: arcnet
    external: true
volumes:
  db2:
