---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  latest:
    image: mcr.microsoft.com/azure-sql-edge
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: sqledge
    deploy:
      mode: replicated
      replicas: 1
    cap_add:
      - SYS_PTRACE    
    ports:
      - 1433
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Passw0rd
      - CONFIG_EDGE_BUILD=0

networks:
  default:
    name: arcnet
    external: true
  
