---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  v21801b4:
    image:  yugabytedb/yugabyte:2.18.0.1-b4
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: yugabyte
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 7001
      - 9000    # admin
      - 5433    # pg
      - 9042    # cassandra
    volumes:
      - v21801b4-src:/home/yugabyte/yb_data    
    command:
      - bin/yugabyted 
      - start
      - --base_dir=/home/yugabyte/yb_data
      - --daemon=false
    networks:
      default:
        aliases:
          - yugabytesql
          - yugabytecql
networks:
  default:
    name: arcnet
    external: true

volumes:
  v21801b4-src: