---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  ubuntu:
    build: .
    tty: true
    command: "/bin/ash"     
    volumes:
    - oraxe:/oradata/oraxe
    - oraee:/oradata/oraee
    - orarac:/oradata/orarac

networks:
  default:
    name: arcnet
    external: true

volumes:
  # https://docs.oracle.com/en/database/oracle/oracle-database/21/racdk/oracle-rac-on-docker.html#GUID-370DABCF-E5AC-48F7-BE1E-15528A42DB85
  oraxe:
    driver: local
    driver_opts:
      type: "nfs"
      # addr = nfs server IP address
      o: addr=${NFS_SERVER},nfsvers=3 #,timeo=600 ,rsize=32768,wsize=32768,actime=0,noac
      # device = dir from NFS server exposing to client
      device: ":/oraxe"
  oraee:
    driver: local
    driver_opts:
      type: "nfs"
      # addr = nfs server IP address
      o: addr=${NFS_SERVER},nfsvers=3 #,timeo=600 ,rsize=32768,wsize=32768,actime=0,noac
      # device = dir from NFS server exposing to client
      device: ":/oraee"
  orarac:
    driver: local
    driver_opts:
      type: "nfs"
      # addr = nfs server IP address
      o: addr=${NFS_SERVER},nfsvers=3 #,timeo=600 ,rsize=32768,wsize=32768,actime=0,noac
      # device = dir from NFS server exposing to client
      device: ":/orarac"            