---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  v109:
    image: mariadb:10.9
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: mariadb
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - LANG=C.UTF-8
    env_file:
      - ../config/env.sh        
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d      
      - v109:/var/lib/mysql
    command: 
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=true               # allow load data local 
      - --secure-file-priv=/tmp           # allow load data
      - --innodb_log_file_size=1073741824 # 1024*1024*1024
    networks:
      default:
        aliases: 
          - mariadb
networks:
  default:
    name: arcnet
    external: true
volumes:
  v109:
