---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - LANG=C.UTF-8
    command: 
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=true
      - --lower_case_table_names=1

networks:
  default:
    name: arcnet
    external: true
