---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  latest:
    image: mysql
    #container_name: mysql
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - LANG=C.UTF-8
    command: 
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=true
      - --innodb_redo_log_capacity=209715200  # 209715200 =  200*1024*1024

networks:
  default:
    name: arcnet
    external: true

