---
# 3.8 required for the volume relative path name to config file 
version: '3.8'

x-mysql: &default-mysql
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: mysql
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
      - LANG=C.UTF-8
    env_file:
      - ../config/env.sh        
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
    command: 
      - mysqld
      - --default-authentication-plugin=mysql_native_password
      - --local-infile=true                    # allow load data local
      - --secure-file-priv=/tmp                # allow load data
      - --innodb_redo_log_capacity=1073741824  # 1024*1024*1024

services:
  src-v8033:
    << : *default-mysql
    image: mysql:8.0.33
    hostname: mysql-src
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - src-v8033:/var/lib/mysql
    networks:
      default:
        aliases: 
          - mysql-src
  dst-v8033:
    << : *default-mysql
    image: mysql:8.0.33
    hostname: mysql-dst
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - dst-v8033:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql-dst
  src-v5742:
    << : *default-mysql
    image: mysql:5.7.42
    hostname: mysql-src
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - src-v5742:/var/lib/mysql
    deploy:
      replicas: 0  
  dst-v5742:
    << : *default-mysql
    image: mysql:5.7.42
    hostname: mysql-dst
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - dst-v5742:/var/lib/mysql
    deploy:
      replicas: 0

networks:
  default:
    name: arcnet
    external: true
volumes:    
  src-v8033:
  src-v5742:  
  dst-v8033:
  dst-v5742:  
