---
# 3.8 required for the volume relative path name to config file 
version: '3.8'

services:
  src-v8033:
    extends: 
      file: ./docker-mysql.yaml
      service: mysql  
    image: mysql:8.0.33
    hostname: mysql-src
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - src-v8033:/var/lib/mysql
    networks:
      default:
        aliases: 
          - mysql
          - mysql-src
  dst-v8033:
    extends: 
      file: ./docker-mysql.yaml
      service: mysql  
    image: mysql:8.0.33
    hostname: mysql-dst
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - dst-v8033:/var/lib/mysql
    networks:
      default:
        aliases:
          - mysql-dst

volumes:    
  src-v8033:
  dst-v8033:
