#!/usr/bin/env bash

psql --username "$POSTGRES_USER" <<EOF
    CREATE USER ${REPLICANT_USER} PASSWORD '${REPLICANT_PW}';
    ALTER USER ${REPLICANT_USER} CREATEDB;
    CREATE DATABASE ${REPLICANT_DB} WITH OWNER ${REPLICANT_USER} ENCODING 'UTF8';
EOF

PGPASSWORD=${REPLICANT_PW} psql --username "${REPLICANT_USER}" --dbname "${REPLICANT_DB}" <<EOF
    CREATE TABLE IF NOT EXISTS "REPLICATE_IO_CDC_HEARTBEAT"(
        TIMESTAMP BIGINT NOT NULL,
        PRIMARY KEY(TIMESTAMP)
    );
EOF