#!/usr/env/bin bash

# src
psql --username "$POSTGRES_USER" <<EOF
CREATE USER ${SRCDB_ARC_USER} PASSWORD '${SRCDB_ARC_PW}';
ALTER USER ${SRCDB_ARC_USER} CREATEDB;
ALTER ROLE ${SRCDB_ARC_USER} WITH REPLICATION;
CREATE DATABASE ${SRCDB_DB} WITH OWNER ${SRCDB_ARC_USER} ENCODING 'UTF8';
EOF

# dst
psql --username "$POSTGRES_USER" <<EOF
CREATE USER ${DSTDB_ARC_USER} PASSWORD '${DSTDB_ARC_PW}';
ALTER USER ${DSTDB_ARC_USER} CREATEDB;
ALTER ROLE ${DSTDB_ARC_USER} WITH REPLICATION;
CREATE DATABASE ${DSTDB_DB} WITH OWNER ${DSTDB_ARC_USER} ENCODING 'UTF8';
EOF