---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  v2022cu4:
    image: mcr.microsoft.com/mssql/server:2022-CU4-ubuntu-20.04
    container_name: sqlserver
    ports:
      - 1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw0rd
      - CONFIG_EDGE_BUILD=0    
networks:
  default:
    name: arcnet
    external: true
