---
# 3.8 required for the volume relative path name to config file 
version: '3.8'

x-free232: &default-free232
    # container_name: must be unqiue and can't replicate
    # hostname: `nmap` and `getent hosts` will show containers with this hostname
    hostname: orafree
    ports:
      - 1521
      - 5500
    environment:
      - DBVER=2320
      - ORACLE_PWD=Passw0rd
      - ORACLE_SID=FREE
      # for the init script 
      - ARCHREDO=/opt/oracle/oradata/FREE/archive_logs
      - REDO=/opt/oracle/oradata/FREE
      - FOOTER_LINES=4      
      - LOGDIR=/opt/oracle/oradata/FREE
    env_file:
      - ../../config/env.sh           
    volumes:
      - ../init.d:/docker-entrypoint-initdb.d/startup


services:
  src:
    # sys and system password: oracle
    << : *default-free232
    build: .
    hostname: orafree-src
    volumes:
      - ../init.d:/docker-entrypoint-initdb.d/startup
      - orafree_v2320-src:/opt/oracle/oradata
    networks:
      default:
        aliases: 
          - orafree
          - orafree-src      

  dst:
    # sys and system password: oracle
    << : *default-free232
    deploy:
      mode: replicated
      replicas: 0    
    image: orafree-v2320-src
    hostname: orafree-dst
    volumes:
      - ../init.d:/docker-entrypoint-initdb.d/startup
      - dst:/opt/oracle/oradata
    networks:
      default:
        aliases: 
          - orafree-dst

networks:
  default:
    name: arcnet
    external: true
volumes:
  ora-shared-rw:
      external: true
      
  orafree_v2320-src:
      external: true

  dst:
