---
# 3.8 required for the volume relative path name to config file 
version: '3.8'
services:
  metadata:
    image: postgres:14-alpine
    container_name: arcion-metadata-test
    ports:
      - 5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Passw0rd 
      - PGCLIENTENCODING=utf-8
    volumes:
      - arcion-metadata:/var/lib/postgresql/data
      - ./init.d:/docker-entrypoint-initdb.d

  ui:
    image:  arcionlabs/replicant-on-premises:test
    ports:
      - 8080
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Passw0rd 
      - ARCION_LICENSE=${ARCION_LICENSE}
      - DB_HOST=arcion-metadata-test
      - DB_PORT=5432
      - DB_DATABASE=arcion
      - DB_USERNAME=arcion
      - DB_PASSWORD=Passw0rd
    volumes:
      - ./arcion-share/data:/data
      - ./arcion-share/config:/config
      - ./arcion-share/libs:/libs
    depends_on:
      - metadata  

  workloads:
    image:  robertslee/arcdemo:test
    ports:
      - 7681
    environment:
      - ARCION_LICENSE=${ARCION_LICENSE}
      - LANG=C.UTF-8
      - METADATA_DB_HOST=arcion-metadata-test
      - METADATA_DB_PORT=5432
      - METADATA_DB_DATABASE=arcion
      - METADATA_DB_USERNAME=arcion
      - METADATA_DB_PASSWORD=Passw0rd
      - PGCLIENTENCODING=utf-8
      # confluent
      - CFLT_ACCESS_KEY_ID=$CFLT_ACCESS_KEY_ID
      - CFLT_SECRET_ACCESS_KEY=$CFLT_SECRET_ACCESS_KEY
      - CFLT_ENDPOINT_SERVER=$CFLT_ENDPOINT_SERVER
      # minio
      - MINIO_ACCESS_KEY_ID=$MINIO_ACCESS_KEY_ID
      - MINIO_SECRET_ACCESS_KEY=$MINIO_SECRET_ACCESS_KEY
      - MINIO_ENDPOINT_SERVER=$MINIO_ENDPOINT_SERVER
      # Snowflake
      - SNOW_ACCESS_KEY_ID=$SNOW_ACCESS_KEY_ID
      - SNOW_SECRET_ACCESS_KEY=$SNOW_SECRET_ACCESS_KEY
      - SNOW_ENDPOINT_SERVER=$SNOW_ENDPOINT_SERVER
      # Google Big Query the key is gzip | base64 -w 0
      - QBG_LOCATION=$QBG_LOCATION	
      - QBG_WAREHOUSE=$QBG_WAREHOUSE
      - QBG_SECRET_ACCESS_KEY=$QBG_SECRET_ACCESS_KEY
      # AWS
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      
    volumes:
      - arcion-bin-23033116:/arcion
      - ./arcion-share/loadgen:/arcion/data
      - ../../arcion-demo/scripts/:/scripts
      - ./arcion-share/data:/data
      - ./arcion-share/config:/config
      - ./arcion-share/libs:/libs
    depends_on:
      - metadata  

volumes:
  arcion-bin-23030115:
    external: true
  arcion-bin-23033116:
    external: true
  arcion-metadata:

networks:
  default:
    name: arcnet
    external: true
