CREATE TABLE YCSBDENSE${SIZE_FACTOR_NAME} (
	YCSB_KEY INT,
	FIELD0 TEXT, FIELD1 TEXT,
	FIELD2 TEXT, FIELD3 TEXT,
	FIELD4 TEXT, FIELD5 TEXT,
	FIELD6 TEXT, FIELD7 TEXT,
	FIELD8 TEXT, FIELD9 TEXT,
	PRIMARY KEY (YCSB_KEY)
)
go

ALTER TABLE  YCSBDENSE${SIZE_FACTOR_NAME} ENABLE CHANGE_TRACKING;
go

EXEC sys.sp_cdc_enable_table  
@source_schema = N'dbo',  
@source_name   = N'YCSBDENSE${SIZE_FACTOR_NAME}',  
@role_name     = NULL,  
@supports_net_changes = 1